FROM golang:1.17-alpine

ADD . /usr/local/src/backend
WORKDIR /usr/local/src/backend

RUN mkdir /usr/backend_01

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /runbackend

EXPOSE 8080



CMD ["/runbackend"]
